# Site wide configuration

title: Cynnefo
locale: en_US
description: We shall not cease from exploration...!
logo: site-logo.png
search: true
url: http://cynnefo.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: RK Kuppala
  avatar: bio-photo.jpg
  email: yogirk1@gmail.com
  disqus-shortname: yogirk
  twitter: Ranjeeth
  facebook: #username
  github: #username
  stackexchange: http://dba.stackexchange.com/users/2193/yogirk
  linkedin: yogirk
  google:
    plus: RKKuppala
    analytics: UA-51329728-1 
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
